export const contentAgentConfig = {
  siteUrl: 'https://logisbase.com',
  defaultCountry: 'us',
  scheduleDescription: 'Weekly, Monday UTC',
  maxAhrefsRowsPerRequest: 10,
  maxAhrefsClustersPerRun: 3,
  allowAhrefsFallbackByDefault: true,
  maxShortlistedTopics: 5,
  maxDraftsPerRun: 1,
  requireExplicitDraftCreation: true,
  topicIdeas: {
    modes: [
      'auto',
      'integration',
      'api-tutorial',
      'software-seo',
      'comparison',
    ],
    integrationTargets: [
      'WordPress and WooCommerce',
      'Shopify',
      'Odoo',
      'ERPNext',
      'NetSuite',
      'Salesforce',
      'HubSpot',
      'QuickBooks',
      'Zapier',
      'Stripe',
      'Twilio',
      'Slack',
    ],
    pillars: [
      'last-mile delivery software',
      'delivery management software',
      'fleet dispatch software',
      'proof of delivery workflows',
      'driver tracking and customer visibility',
      'route optimization and dispatch planning',
      'LogisBase API tutorials',
      'webhook-driven logistics automation',
      'source-available logistics software',
      'logistics integrations for ERP and CRM systems',
    ],
    examples: [
      'Integrating LogisBase with WordPress and WooCommerce for delivery workflows',
      'Connecting Shopify orders to LogisBase dispatch',
      'Building proof of delivery workflows with the LogisBase API',
      'Connecting Odoo or ERPNext to LogisBase for last-mile fulfillment',
      'Using LogisBase webhooks to sync delivery status into Salesforce or HubSpot',
      'Comparing LogisBase with Onfleet for source-available last-mile delivery software',
      'Building customer delivery tracking with LogisBase and webhooks',
      'Automating dispatch from NetSuite or QuickBooks into LogisBase',
    ],
  },
  featureImage: {
    enabledByDefault: true,
    model: 'gpt-image-1.5',
    size: '1536x1024',
    quality: 'auto',
    outputFormat: 'png',
    styleGuide:
      'Create clean editorial logistics software imagery. Use abstract dashboards, delivery routes, warehouse or fleet operations, and modern supply-chain UI motifs. Avoid text, logos, brand marks, distorted UI labels, people close-ups, and generic stock-photo compositions.',
  },
  contentStrategy: {
    defaultFocusByUtcDay: {
      1: 'logistics-software',
      3: 'logisbase-api-tutorial',
      5: 'supply-chain-software',
    },
    allowedFocuses: [
      'logistics-software',
      'supply-chain-software',
      'logisbase-api-tutorial',
    ],
    requiredRelevance:
      'Topics must be specific to LogisBase, Fleet-Ops, last-mile delivery software, delivery management, courier dispatch, proof of delivery, driver tracking, route optimization, or building delivery workflows with the LogisBase API.',
    contentMix:
      'Use Monday runs for last-mile delivery software SEO, Wednesday runs for LogisBase API/tutorial articles, and Friday runs for competitor-alternative or proof-of-delivery SEO. Avoid broad supply-chain keywords until Pallet, Ledger, and Storefront are the primary content focus.',
    tutorialExamples: [
      'build a delivery tracking workflow with the LogisBase API',
      'create proof of delivery workflows with LogisBase',
      'connect LogisBase webhooks to an order management system',
      'build a dispatch dashboard with LogisBase APIs',
      'set up route planning and driver assignment in LogisBase',
    ],
    editorialRules: [
      'LogisBase should be positioned as serious logistics, fleet operations, and last-mile delivery software for SMB and enterprise teams. Do not use outdated "API-first" positioning.',
      'Spell Fleet-Ops exactly as "Fleet-Ops". Do not write "FleetOps".',
      'Refer to Fleet-Ops as Fleet-Ops, not "Fleet-Ops extension".',
      'Do not tell readers to install, enable, activate, add, or turn on Fleet-Ops, Pallet, Storefront, Ledger, or other core LogisBase extensions. Core LogisBase extensions are bundled, installed, and active by default in LogisBase Cloud and standard self-hosted LogisBase.',
      'The LogisBase website is https://logisbase.com and the documentation URL is https://logisbase.com/docs.',
      'Manage order configs at Fleet-Ops -> Operations -> Order Config. Do not call this screen "Order Configurations".',
      'Activity definitions are configured by the order config; do not invent platform-level activity definitions.',
      'For Uber-like or ad hoc order flows, create orders with adhoc: true and use adhoc_distance to set the driver broadcast radius in meters.',
      'Ad hoc orders are broadcast to drivers near the pickup. Drivers accept or decline in Navigator; do not require manual dispatch, manual driver assignment, or orchestrator allocation for that flow.',
      'For service quote queries, do not use an order_config parameter. Use service for the service rate ID, defaulting to all, and serviceType for the order config type derived from the order_config key.',
      'Proof of delivery for an order is available at /v1/orders/:id/proofs.',
      'For realtime driver location, subscribe to the LogisBase SocketCluster instance using the accepted driver channel.',
      'When writing API tutorials, verify endpoint names, request parameters, and resource names against the indexed API docs or cloned source context.',
      'Do not name API request fields, query parameters, response properties, webhook fields, or configuration keys unless the exact name appears in sourceContext and is cited in sourceCitations.',
    ],
  },
  ahrefs: {
    apiBaseUrl: 'https://api.ahrefs.com/v3',
    keywordEndpoint: '/keywords-explorer/matching-terms',
    matchMode: 'terms',
    terms: 'all',
    keywordSelectFields: [
      'keyword',
      'volume',
      'difficulty',
      'traffic_potential',
      'parent_topic',
      'intents',
    ],
  },
  seedClusters: [
    'last mile delivery software',
    'delivery management software',
    'delivery dispatch software',
    'courier dispatch software',
    'proof of delivery software',
    'delivery tracking software',
    'delivery route optimization software',
    'onfleet alternatives',
    'onfleet competitors',
    'tookan alternatives',
    'detrack alternatives',
    'source-available delivery management software',
    'source-available last mile delivery software',
    'route optimization API',
    'dispatch API',
    'delivery tracking API',
    'proof of delivery API',
    'last mile delivery API',
  ],
  seedClustersByFocus: {
    'logistics-software': [
      'last mile delivery software',
      'delivery management software',
      'onfleet alternatives',
    ],
    'supply-chain-software': [
      'proof of delivery software',
      'delivery route optimization software',
      'detrack alternatives',
    ],
    'logisbase-api-tutorial': [
      'delivery tracking API',
      'proof of delivery API',
      'dispatch API',
    ],
  },
  fallbackOpportunitiesByFocus: {
    'logistics-software': [
      {
        keyword: 'onfleet alternatives',
        cluster: 'competitor-alternatives',
        parentTopic: 'last mile delivery software',
        intents: ['commercial', 'comparison'],
      },
      {
        keyword: 'last mile delivery software',
        cluster: 'last-mile-delivery-software',
        parentTopic: 'delivery management software',
        intents: ['commercial'],
      },
      {
        keyword: 'delivery dispatch software',
        cluster: 'delivery-dispatch-software',
        parentTopic: 'dispatch software',
        intents: ['commercial'],
      },
      {
        keyword: 'courier dispatch software',
        cluster: 'courier-dispatch-software',
        parentTopic: 'courier management software',
        intents: ['commercial'],
      },
    ],
    'supply-chain-software': [
      {
        keyword: 'detrack alternatives',
        cluster: 'competitor-alternatives',
        parentTopic: 'proof of delivery software',
        intents: ['commercial', 'comparison'],
      },
      {
        keyword: 'proof of delivery software',
        cluster: 'proof-of-delivery-software',
        parentTopic: 'delivery management software',
        intents: ['commercial'],
      },
      {
        keyword: 'delivery route optimization software',
        cluster: 'route-optimization-software',
        parentTopic: 'delivery management software',
        intents: ['commercial'],
      },
    ],
    'logisbase-api-tutorial': [
      {
        keyword: 'delivery tracking API',
        cluster: 'delivery-api-tutorial',
        parentTopic: 'delivery tracking API',
        intents: ['informational', 'developer'],
      },
      {
        keyword: 'proof of delivery API',
        cluster: 'proof-of-delivery-api',
        parentTopic: 'proof of delivery API',
        intents: ['informational', 'developer'],
      },
      {
        keyword: 'dispatch API',
        cluster: 'dispatch-api',
        parentTopic: 'dispatch API',
        intents: ['informational', 'developer'],
      },
    ],
  },
  competitorDomains: [
    'onfleet.com',
    'jungleworks.com',
    'detrack.com',
    'routific.com',
    'dispatchtrack.com',
    'locate2u.com',
    'onro.io',
    'route4me.com',
    'bringg.com',
    'shipday.com',
    'track-pod.com',
  ],
  context: {
    maxSelectedFiles: 24,
    maxCharsPerFile: 1800,
    budgets: {
      scoring: {
        maxSelectedFiles: 12,
        maxCharsPerSource: 900,
        maxTotalChars: 12000,
      },
      drafting: {
        maxSelectedFiles: 18,
        maxCharsPerSource: 1200,
        maxTotalChars: 18000,
      },
    },
    includeGlobs: [
      'src/app/**/page.tsx',
      'src/app/**/*page-content.tsx',
      'content/docs/**/*.mdx',
      'README.md',
    ],
    excludePathParts: [
      'node_modules',
      '.next',
      '.source',
      'vendor/postman',
      'public/',
    ],
  },
  sourceTruthRepos: [
    {
      repo: 'logisbase/core-api',
      path: 'source-truth/core-api',
      category: 'backend-api',
      includeGlobs: [
        'routes/**/*.php',
        'src/Http/Controllers/**/*.php',
        'src/Http/Requests/**/*.php',
        'src/Http/Resources/**/*.php',
        'src/Models/**/*.php',
        'src/Policies/**/*.php',
        'src/Services/**/*.php',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'logisbase/fleetops',
      path: 'source-truth/fleetops',
      category: 'fleetops',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'logisbase/ledger',
      path: 'source-truth/ledger',
      category: 'ledger',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'logisbase/storefront',
      path: 'source-truth/storefront',
      category: 'storefront',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'logisbase/dev-engine',
      path: 'source-truth/dev-engine',
      category: 'developer-platform',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'logisbase/iam-engine',
      path: 'source-truth/iam-engine',
      category: 'identity-access',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'logisbase/ember-core',
      path: 'source-truth/ember-core',
      category: 'frontend-core',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'src/**/*.{js,ts,hbs}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'logisbase/pallet',
      path: 'source-truth/pallet',
      category: 'pallet',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'logisbase/postman',
      path: 'vendor/postman',
      category: 'api-collections',
      includeGlobs: ['**/*.json', '**/*.md'],
    },
  ],
  ghost: {
    apiVersion: 'v5.0',
    internalTags: ['#ai-generated', '#needs-review', '#seo-content-agent'],
  },
};
