import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | LogisBase',
  description:
    'LogisBase Terms of Service for SaaS and Cloud customers. Read our terms covering usage, data, billing, and your rights as a customer.',
  alternates: { canonical: 'https://logisbase.com/terms' },
  openGraph: {
    title: 'Terms of Service | LogisBase',
    description: 'LogisBase Terms of Service for SaaS and Cloud customers.',
  },
  twitter: {
    card: 'summary_large_image',
    title: `Terms of Service | LogisBase`,
    description: `LogisBase Terms of Service for SaaS and Cloud customers.`,
  },
};

const LAST_UPDATED = 'April 2025';
const EFFECTIVE_DATE = '1 April 2025';

export default function TermsOfServicePage() {
  return (
    <div className="section-padding">
      <div className="container mx-auto max-w-4xl px-4">
        {/* Header */}
        <div className="mb-12">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs">
            <span className="text-primary">●</span>
            <span>Legal</span>
          </div>
          <h1 className="mb-4 text-4xl font-bold tracking-tight md:text-5xl">
            Terms of Service
          </h1>
          <p className="text-muted-foreground">
            Last updated: {LAST_UPDATED} &nbsp;·&nbsp; Effective date:{' '}
            {EFFECTIVE_DATE}
          </p>
          <p className="text-muted-foreground mt-2 text-sm">
            These Terms of Service (&ldquo;Terms&rdquo;) govern your access to
            and use of the LogisBase Cloud platform and associated services
            provided by <strong>LogisBase Ltd.</strong>{' '}
            (&ldquo;LogisBase&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or
            &ldquo;our&rdquo;), a company incorporated in Nigeria. By accessing
            or using our services, you agree to be bound by these Terms.
          </p>
        </div>

        {/* Table of Contents */}
        <div className="bg-muted/30 mb-12 rounded-xl border p-6">
          <h2 className="mb-4 font-semibold">Table of Contents</h2>
          <ol className="text-muted-foreground list-inside list-decimal space-y-1.5 text-sm">
            {[
              'Definitions',
              'Acceptance of Terms',
              'Account Registration',
              'LogisBase Cloud Services',
              'Billing and Payment',
              'Resource Units and Usage',
              'Acceptable Use Policy',
              'Intellectual Property',
              'Data and Privacy',
              'Source-accessible Licensing',
              'Confidentiality',
              'Warranties and Disclaimers',
              'Limitation of Liability',
              'Indemnification',
              'Termination',
              'Governing Law',
              'Changes to Terms',
              'Contact Information',
            ].map((item, i) => (
              <li key={item}>
                <a
                  href={`#section-${i + 1}`}
                  className="hover:text-primary transition-colors"
                >
                  {item}
                </a>
              </li>
            ))}
          </ol>
        </div>

        {/* Sections */}
        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-10">
          <section id="section-1">
            <h2 className="mb-4 text-2xl font-bold">1. Definitions</h2>
            <p className="text-muted-foreground leading-relaxed">
              In these Terms, the following definitions apply:
            </p>
            <ul className="text-muted-foreground mt-3 space-y-2 text-sm">
              <li>
                <strong>&ldquo;Service&rdquo;</strong> means the LogisBase Cloud
                platform, including all software, APIs, documentation, and
                related services provided by LogisBase.
              </li>
              <li>
                <strong>&ldquo;Customer&rdquo;</strong> or{' '}
                <strong>&ldquo;you&rdquo;</strong> means the individual or
                entity that has registered for and is using the Service.
              </li>
              <li>
                <strong>&ldquo;Subscription&rdquo;</strong> means a paid plan
                granting access to the Service for a defined billing period.
              </li>
              <li>
                <strong>&ldquo;Resource Units&rdquo;</strong> means the usage
                credits consumed by platform resources (orders, users, vehicles,
                drivers, webhooks, API keys) as defined in the applicable
                pricing schedule.
              </li>
              <li>
                <strong>&ldquo;Customer Data&rdquo;</strong> means all data
                submitted, uploaded, or generated by you through the Service.
              </li>
              <li>
                <strong>&ldquo;Extension&rdquo;</strong> means a custom module
                or integration developed by or for the Customer on top of the
                LogisBase platform.
              </li>
            </ul>
          </section>

          <section id="section-2">
            <h2 className="mb-4 text-2xl font-bold">2. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By creating an account, accessing, or using the Service, you
              confirm that you are at least 18 years of age, have the legal
              authority to enter into these Terms on behalf of yourself or your
              organisation, and agree to comply with all applicable laws and
              regulations. If you do not agree to these Terms, you must not
              access or use the Service.
            </p>
          </section>

          <section id="section-3">
            <h2 className="mb-4 text-2xl font-bold">3. Account Registration</h2>
            <p className="text-muted-foreground leading-relaxed">
              To access the Service, you must register for an account by
              providing accurate and complete information. You are responsible
              for maintaining the confidentiality of your account credentials
              and for all activities that occur under your account. You must
              notify us immediately at{' '}
              <a
                href="mailto:support@logisbase.com"
                className="text-primary underline underline-offset-4"
              >
                support@logisbase.com
              </a>{' '}
              if you suspect any unauthorised access to your account. LogisBase
              reserves the right to suspend or terminate accounts that provide
              false information or violate these Terms.
            </p>
          </section>

          <section id="section-4">
            <h2 className="mb-4 text-2xl font-bold">
              4. LogisBase Cloud Services
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              LogisBase provides a fully managed, multi-tenant cloud platform
              for logistics operations management. Subject to your Subscription
              and these Terms, LogisBase grants you a limited, non-exclusive,
              non-transferable right to access and use the Service during your
              Subscription term. The Service includes access to all platform
              modules (FleetOps, Storefront, Pallet, Ledger, Navigator,
              Developer Console, IAM) as available under your plan.
            </p>
            <p className="text-muted-foreground mt-3 leading-relaxed">
              We target 99.9% monthly uptime for the Service. Scheduled
              maintenance windows will be communicated with at least 24
              hours&apos; notice where possible. LogisBase is not liable for
              downtime caused by circumstances beyond our reasonable control.
            </p>
          </section>

          <section id="section-5">
            <h2 className="mb-4 text-2xl font-bold">5. Billing and Payment</h2>
            <p className="text-muted-foreground leading-relaxed">
              Subscriptions are billed in advance on a monthly or annual basis.
              All fees are quoted in USD and are non-refundable except as
              expressly stated in these Terms or required by applicable law.
              Annual subscriptions receive a 20% discount (equivalent to two
              months free) compared to the monthly rate.
            </p>
            <p className="text-muted-foreground mt-3 leading-relaxed">
              You authorise LogisBase to charge your payment method on file for
              all applicable fees. If payment fails, we will notify you and may
              suspend access to the Service after a grace period of 7 days.
              Overdue amounts accrue interest at 1.5% per month. You are
              responsible for all taxes applicable to your use of the Service.
            </p>
          </section>

          <section id="section-6">
            <h2 className="mb-4 text-2xl font-bold">
              6. Resource Units and Usage
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Your Subscription includes a monthly allocation of Resource Units.
              Different platform resources consume Resource Units as follows:
              Orders (2 units), Users (5 units), Vehicles (1 unit), Drivers (1
              unit), Webhooks (5 units), API Keys (1 unit). Usage beyond your
              monthly allocation is charged at the overage rate applicable to
              your plan.
            </p>
            <p className="text-muted-foreground mt-3 leading-relaxed">
              Unused Resource Units from your monthly allocation do not roll
              over to the next billing period. Resource Unit Top-Up Packs
              purchased separately do not expire and remain in your account
              until used. You can monitor your usage in real-time from your
              billing dashboard within the LogisBase console.
            </p>
          </section>

          <section id="section-7">
            <h2 className="mb-4 text-2xl font-bold">
              7. Acceptable Use Policy
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to use the Service to:
            </p>
            <ul className="text-muted-foreground mt-3 list-inside list-disc space-y-2 text-sm">
              <li>
                Violate any applicable law, regulation, or third-party rights.
              </li>
              <li>Transmit malicious code, viruses, or disruptive data.</li>
              <li>
                Attempt to gain unauthorised access to any part of the Service
                or its infrastructure.
              </li>
              <li>
                Reverse engineer, decompile, or disassemble any part of the
                Service (except as permitted by applicable law).
              </li>
              <li>
                Resell, sublicense, or transfer access to the Service without
                our prior written consent.
              </li>
              <li>
                Use the Service in a manner that could damage, disable, or
                impair its performance.
              </li>
              <li>
                Collect or harvest any personal data from other users of the
                Service.
              </li>
            </ul>
            <p className="text-muted-foreground mt-3 leading-relaxed">
              LogisBase reserves the right to suspend or terminate your access
              immediately if we determine, in our sole discretion, that you have
              violated this Acceptable Use Policy.
            </p>
          </section>

          <section id="section-8">
            <h2 className="mb-4 text-2xl font-bold">
              8. Intellectual Property
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              LogisBase retains all intellectual property rights in the Service,
              including the LogisBase Core platform, trademarks, logos, and
              documentation. Nothing in these Terms transfers any ownership of
              LogisBase&apos;s intellectual property to you.
            </p>
            <p className="text-muted-foreground mt-3 leading-relaxed">
              You retain all intellectual property rights in your Customer Data
              and any Extensions developed exclusively for your use. LogisBase
              shall not use, reproduce, or distribute your Customer Data or
              Extensions without your prior written consent, except as necessary
              to provide the Service.
            </p>
          </section>

          <section id="section-9">
            <h2 className="mb-4 text-2xl font-bold">9. Data and Privacy</h2>
            <p className="text-muted-foreground leading-relaxed">
              Your use of the Service is also governed by our{' '}
              <Link
                href="/privacy"
                className="text-primary underline underline-offset-4"
              >
                Privacy Policy
              </Link>
              , which is incorporated into these Terms by reference. By using
              the Service, you consent to the collection and use of your data as
              described in the Privacy Policy.
            </p>
            <p className="text-muted-foreground mt-3 leading-relaxed">
              LogisBase processes Customer Data solely to provide and improve
              the Service. We implement industry-standard security measures to
              protect Customer Data, including encryption at rest and in
              transit, access controls, and regular security audits. We do not
              sell Customer Data to third parties.
            </p>
          </section>

          <section id="section-10">
            <h2 className="mb-4 text-2xl font-bold">
              10. Source-accessible Licensing
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The LogisBase Core platform is licensed under the
              (Source-accessible). Your use of the Service via LogisBase Cloud
              does not require you to source-accessible your own applications or
              data. However, if you self-host LogisBase and modify the Core,
              Source-accessible obligations may apply.
            </p>
            <p className="text-muted-foreground mt-3 leading-relaxed">
              If you require a Commercial License to build proprietary
              Extensions or integrations without Source-accessible obligations,
              separate commercial licensing terms apply. See our{' '}
              <Link
                href="/licensing/commercial"
                className="text-primary underline underline-offset-4"
              >
                Commercial Licensing page
              </Link>{' '}
              for full details, pricing, and FAQ, or contact{' '}
              <a
                href="mailto:hello@logisbase.com"
                className="text-primary underline underline-offset-4"
              >
                hello@logisbase.com
              </a>
              .
            </p>
          </section>

          <section id="section-11">
            <h2 className="mb-4 text-2xl font-bold">11. Confidentiality</h2>
            <p className="text-muted-foreground leading-relaxed">
              Each party agrees to keep confidential all non-public information
              disclosed by the other party that is designated as confidential or
              that reasonably should be understood to be confidential. This
              obligation does not apply to information that is publicly
              available, independently developed, or required to be disclosed by
              law. Confidentiality obligations survive termination of these
              Terms for a period of three (3) years.
            </p>
          </section>

          <section id="section-12">
            <h2 className="mb-4 text-2xl font-bold">
              12. Warranties and Disclaimers
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              LogisBase warrants that the Service will perform materially in
              accordance with its documentation under normal use. TO THE MAXIMUM
              EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED
              &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo;. FLEETBASE
              DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
              IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
              PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </section>

          <section id="section-13">
            <h2 className="mb-4 text-2xl font-bold">
              13. Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW,
              FLEETBASE&apos;S TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS
              ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT
              EXCEED THE FEES PAID BY YOU TO FLEETBASE IN THE THREE (3) MONTHS
              PRECEDING THE CLAIM. IN NO EVENT SHALL FLEETBASE BE LIABLE FOR ANY
              INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
              INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, EVEN IF ADVISED OF
              THE POSSIBILITY OF SUCH DAMAGES.
            </p>
          </section>

          <section id="section-14">
            <h2 className="mb-4 text-2xl font-bold">14. Indemnification</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to indemnify, defend, and hold harmless LogisBase and
              its officers, directors, employees, and agents from and against
              any claims, liabilities, damages, losses, and expenses (including
              reasonable legal fees) arising out of or in any way connected with
              your access to or use of the Service, your violation of these
              Terms, or your infringement of any third-party rights.
            </p>
          </section>

          <section id="section-15">
            <h2 className="mb-4 text-2xl font-bold">15. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              Either party may terminate these Terms upon written notice if the
              other party materially breaches these Terms and fails to cure such
              breach within 30 days of written notice. You may cancel your
              Subscription at any time through your account settings or by
              contacting{' '}
              <a
                href="mailto:support@logisbase.com"
                className="text-primary underline underline-offset-4"
              >
                support@logisbase.com
              </a>
              . Cancellations take effect at the end of the current billing
              period; no refunds are provided for unused periods.
            </p>
            <p className="text-muted-foreground mt-3 leading-relaxed">
              Upon termination, your access to the Service will cease. You may
              export your Customer Data for up to 30 days following termination,
              after which it will be deleted in accordance with our data
              retention policy.
            </p>
          </section>

          <section id="section-16">
            <h2 className="mb-4 text-2xl font-bold">16. Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms are governed by and construed in accordance with the
              laws of Nigeria, without regard to its conflict of law provisions.
              Any disputes arising out of or in connection with these Terms
              shall be subject to the exclusive jurisdiction of the courts of
              Nigeria.
            </p>
          </section>

          <section id="section-17">
            <h2 className="mb-4 text-2xl font-bold">17. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              LogisBase reserves the right to modify these Terms at any time. We
              will notify you of material changes by email or by posting a
              notice on our website at least 30 days before the changes take
              effect. Your continued use of the Service after the effective date
              constitutes acceptance of the updated Terms. If you do not agree
              to the changes, you must stop using the Service before the
              effective date.
            </p>
          </section>

          <section id="section-18">
            <h2 className="mb-4 text-2xl font-bold">18. Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms, please contact us:
            </p>
            <div className="bg-muted/30 mt-4 space-y-1.5 rounded-lg border p-4 text-sm">
              <div>
                <strong>LogisBase Ltd.</strong>
              </div>
              <div>
                Email:{' '}
                <a
                  href="mailto:hello@logisbase.com"
                  className="text-primary underline underline-offset-4"
                >
                  hello@logisbase.com
                </a>
              </div>
              <div>
                Support:{' '}
                <a
                  href="mailto:support@logisbase.com"
                  className="text-primary underline underline-offset-4"
                >
                  support@logisbase.com
                </a>
              </div>
              <div>Phone: +65 9780 3731</div>
              <div>
                Website:{' '}
                <Link
                  href="/"
                  className="text-primary underline underline-offset-4"
                >
                  logisbase.com
                </Link>
              </div>
            </div>
          </section>
        </div>

        {/* Footer nav */}
        <div className="mt-16 flex flex-col items-start justify-between gap-4 border-t pt-8 sm:flex-row sm:items-center">
          <div className="text-muted-foreground text-sm">
            See also:{' '}
            <Link
              href="/privacy"
              className="text-primary mr-3 underline underline-offset-4"
            >
              Privacy Policy
            </Link>
            <Link
              href="/licensing"
              className="text-primary underline underline-offset-4"
            >
              Licensing
            </Link>
          </div>
          <div className="text-muted-foreground text-xs">
            &copy; {new Date().getFullYear()} LogisBase Ltd. All rights
            reserved.
          </div>
        </div>
      </div>
    </div>
  );
}
